name = "x-gate"
main = "worker/src/index.ts"
compatibility_date = "2025-09-15"

# 로컬 미리보기: wrangler dev
# 배포: wrangler deploy

[vars]
# 사전 검증된 '상호팔로우+초대조건 충족' 사용자 목록 (숫자 Twitter ID 문자열)
ALLOWLIST_JSON = '["1542749919810686976","987654"]'

# 초대코드 -> userId 배열(최대 3개)
INVITES_JSON = '{"CODE123":["1111","2222"],"BETA999":["3333"]}'

# GitHub Pages에서 보호페이지 파일 경로 (리다이렉트 목적)
PROTECTED_PAGE_URL = "https://nugulnugu.github.io/X-Release/protected.html"
HOME_PAGE_URL      = "https://nugulnugu.github.io/X-Release/"

[env.production.vars]
ALLOWED_ORIGIN = "https://nugulnugu.github.io"

# 아래 비밀키들은 대시보드에 환경변수로 바인딩 권장(또는 wrangler secret)
# X_CLIENT_ID, X_CLIENT_SECRET, JWT_SECRET, OAUTH_REDIRECT_URL 등
